### ISSUE TITLE
級が分からない問題がある

### ISSUE THREAD

**Issue by TateIsuKanna** [TateIsuKanna/sofen_learnkanken#12]
Sheet9とSheet10の順番が逆になってるけど，どっちがどっち

**Comment by TateIsuKanna** [comment]
あとファイル名，級にした方がいい?

**Comment by sino-I** [comment]
あ、なんか違うところにコメントしてた。

**Comment by sino-I** [comment]
ファイル名にこだわりはないので分かりやすいようにしてください。

**Comment by TateIsuKanna** [comment]
難度って考えるならこのままでいいのだけれど，級にこだわるんだったら変えた方がいいかなって．(でも『準1』はどうする?)
他の人の意見も待ってみる．

**Comment by aste-4** [comment]
級のほうが直感的な気はします
英検のページですが http://www.eiken.or.jp/eiken/exam/languages/#anc01 では準1級と準2級に"pre"を使ってます
