### ISSUE TITLE
同じ問題が表示される・・・?

### ISSUE THREAD

**Issue by TateIsuKanna** [TateIsuKanna/sofen_learnkanken#14]
再現方法が分からない．

**Comment by aste-4** [comment]
[question/1.csv](https://github.com/TateIsuKanna/sofen_learnkanken/blob/3c222895b287c1b7921141b83e6b9b2663859df3/questions/1.csv)に「学校」という問題が重複登録されている影響ではない?(L9,L29)
それ以外では今のところ確認できず
