### ISSUE TITLE
出題

### ISSUE THREAD

**Issue by TateIsuKanna** [TateIsuKanna/sofen_learnkanken#3]

**Comment by TateIsuKanna** [comment]
最初の5問で不正解だったのって次の5問で出たっけ?

**Comment by sino-I** [comment]
出題は正解していない問題からランダム抽選だから出る可能性もあるんじゃない

**Comment by TateIsuKanna** [comment]
C++17からランダムサンプリングが使える~~何で今まで無かった~~．演習室の環境で使えるかな?悲しいgcc4.9.3
http://en.cppreference.com/w/cpp/algorithm/sample
