### ISSUE TITLE
記録保存

### ISSUE THREAD

**Issue by TateIsuKanna** [TateIsuKanna/sofen_learnkanken#4]

**Comment by TateIsuKanna** [comment]
問題ファイルとセーブファイルは分けますか?

**Comment by sino-I** [comment]
それぞれの場合の大まかな挙動はどんな感じになる想定ですか。

**Comment by TateIsuKanna** [comment]
大まかな挙動というか違い?
- 分けた場合
セーブファイルが無ければ全て未正解とする．終了時にセーブファイルを保存．問題毎にセーブファイルは作成．
- 分けない場合
`問題 答え 正解したかどうか`
という形で問題ファイルに書くとしたら，正解したかどうかが書いてあるファイルと，書いて無いただの問題ファイルの2種類を読めるようにするようで面倒．

**Comment by TateIsuKanna** [comment]
それとCSVじゃなくてTSV(or SSV)にしました．面倒なので．

**Comment by sino-I** [comment]
分けた場合の行間に隠されたデメリット等がないのであれば、それを読む限りでは分ければいいのではと思います。
まあ、作成者がやり易い形でやっていただければ。
